/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Hombre-13.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Man13(props) {
  const { nodes, materials } = useGLTF("/Hombre-13.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Cuerpo_Masculino_9.geometry}
        material={materials.initialShadingGroup}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cuerpo_Masculino_13.geometry}
        material={materials["initialShadingGroup.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Hombre-13.glb");
