/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Hombre-4.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Man4(props) {
  const { nodes, materials } = useGLTF("/Hombre-4.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cuerpo_Masculino_4.geometry}
        material={materials["initialShadingGroup.004"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Hombre-4.glb");
