import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { AppProvider } from "~/utils/context";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <AppProvider>
        <body>{children}</body>
      </AppProvider>
    </html>
  );
}
